# HTTP request the 'json' file for jenkins
update_center_url = "http://updates.jenkins-ci.org/update-center.json"

# remove the front and back temporarily for pure json parsing
suppress_front = "updateCenter.post("
suppress_back = ");"

# url replacments
connection_check_url_change = "http://penguin.dso"
url_replace_from = "updates.jenkins-ci.org"
url_replace_into = "penguin.dso/jenkins"

# json output
auto_create_output_dir = true
modified_json_file_path = "/home/weiguang/repo-sync/repos/repo/jenkins/update-center.json" 
url_list_json_file_path = "/home/weiguang/repo-sync/sync-scripts/jenkins-sync/output/url-list.json"
